## ✏️ Exercícios de Fixação

In [3]:
import numpy as np

### Exercício 1 — Fácil: Criando e inspecionando matrizes

**Enunciado:** Crie as seguintes matrizes e exiba o `shape`, `ndim` e `size` de cada uma:

a) Uma matriz 3×3 com os valores de 1 a 9 (use `arange` + `reshape`).  
b) Uma matriz de zeros com 4 linhas e 2 colunas.  
c) A matriz identidade de tamanho 3.

> 💡 **Dica:** Para o item (a), crie primeiro o array com `np.arange(1, 10)` e depois use `.reshape(3, 3)`.

a) *Resposta*

In [15]:
matriz = np.arange(1, 10)
print(matriz)

matriz_3x3 = matriz.reshape(3, 3)
print('Matriz 3x3: \n', matriz_3x3)

print(f'shape: {matriz_3x3.shape}, size: {matriz_3x3.size}, ndim: {matriz_3x3.ndim}')



[1 2 3 4 5 6 7 8 9]
Matriz 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3), size: 9, ndim: 2


b) *Resposta*

In [16]:
matriz_zeros = np.zeros((4,2))
print("Matriz_zeros: \n", matriz_zeros)

print(f'shape: {matriz_zeros.shape}, size: {matriz_zeros.size}, ndim: {matriz_zeros.ndim}')

Matriz_zeros: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
shape: (4, 2), size: 8, ndim: 2


c) *Resposta*

In [20]:
matriz_ident = np.eye(3)
print('Matriz Identidade 3: \n', matriz_ident)
print(f'shape: {matriz_ident.shape}, size: {matriz_ident.size}, ndim: {matriz_ident.ndim}')

Matriz Identidade 3: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (3, 3), size: 9, ndim: 2


### Exercício 2 — Fácil: Indexação e fatiamento

**Enunciado:** Dada a matriz de temperaturas diárias de 3 cidades ao longo de 5 dias:

```python
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])
```

Extraia:
- A temperatura da Cidade B no 3º dia (índice 2).
- Todas as temperaturas da Cidade C.
- As temperaturas de todas as cidades no último dia.
- A submatriz das cidades A e B nos primeiros 3 dias.

> 💡 **Dica:** Para "último dia", use índice `-1` na coluna. Para a submatriz, lembre que o fim do slice é exclusivo.

In [24]:
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])

# Temperatura na Cidade B no 3º Dia
print('Temperatura do 3º Dia na Cidade B: ', temperaturas[1, 2])

#Todas as Temperaturas da Cidade C
print('Temperaturas da Cidade C: ', temperaturas[-1, :])

#Temperaturas de Todas as Cidades no último Dia
print('Temperaturas do último dia em todas as Cidades: ', temperaturas[:, -1])

#submatriz das Cidadades A e B nos 3 primeiros dias
print('Temperaturas das Cidades A e B do primeiro ao terceiro dia: \n', temperaturas[0:2, 0:3])

Temperatura do 3º Dia na Cidade B:  30
Temperaturas da Cidade C:  [22 24 21 23 25]
Temperaturas do último dia em todas as Cidades:  [35 29 25]
Temperaturas das Cidades A e B do primeiro ao terceiro dia: 
 [[32 33 31]
 [28 27 30]]


### Exercício 3 — Médio: Reshape, flatten e estatísticas por eixo

**Enunciado:** Você tem as vendas mensais de uma loja ao longo de um ano, registradas em um array 1D de 12 elementos (Janeiro a Dezembro):

```python
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
```

1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa um mês dentro do trimestre.
2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).
3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).
4. Identifique o trimestre com maior faturamento.
5. Use `flatten()` para recuperar o array original.

> 💡 **Dica:** Para o item 4, use `np.argmax()` no array de totais. Lembre que o índice retornado começa em 0 — some 1 para obter o número do trimestre.

In [10]:
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])

1. *Resposta*

In [ ]:
#Array organizado por matriz 4x3

vendas_trimestre = vendas_ano.reshape(4, 3)
print("Vendas Trimestre: \n", vendas_trimestre)

Vendas Trimestre: 
 [[45 52 48]
 [60 55 70]
 [80 78 65]
 [58 50 90]]


2. *Resposta*

In [ ]:
#Total de Vendas por Trimestre

tri1 = vendas_trimestre[0, :].sum()
print('Total de Vendas no 1TRI: ', tri1)
tri2 = vendas_trimestre[1, :].sum()
print('Total de Vendas no 2TRI: ', tri2)
tri3 = vendas_trimestre[2, :].sum()
print('Total de Vendas no 3TRI: ', tri3)
tri4 = vendas_trimestre[3, :].sum()
print('Total de Vendas no 4TRI: ', tri4)

Total de Vendas no 1TRI:  145
Total de Vendas no 2TRI:  185
Total de Vendas no 3TRI:  223
Total de Vendas no 4TRI:  198


3. *Resposta*

In [23]:
#Média de Vendas por trimestre

media_tri1 = vendas_trimestre[0, :].mean().round(2)
print('Média de Vendas no 1TRI: ', media_tri1)
media_tri2 = vendas_trimestre[1, :].mean().round(2)
print('Média de Vendas no 2TRI: ', media_tri2)
media_tri3 = vendas_trimestre[2, :].mean().round(2)
print('Média de Vendas no 3TRI: ', media_tri3)
media_tri4 = vendas_trimestre[3, :].mean().round(2)
print('Media de Vendas no 4TRI: ', media_tri4)

Média de Vendas no 1TRI:  48.33
Média de Vendas no 2TRI:  61.67
Média de Vendas no 3TRI:  74.33
Media de Vendas no 4TRI:  66.0


4. *Resposta*

5. *Resposta*

In [8]:
vendas_year = vendas_trimestre.flatten()
print("Array Original: ", vendas_year)

Array Original:  [45 52 48 60 55 70 80 78 65 58 50 90]


### Exercício 4 — Médio: Operações e transposição

**Enunciado:** Uma escola tem as notas de 3 alunos em 4 matérias:

```python
notas = np.array([
    [7.0, 8.5, 6.0, 9.0],   # Aluno 1: Mat, Port, Hist, Cien
    [9.0, 7.5, 8.0, 8.5],   # Aluno 2
    [6.5, 9.0, 7.5, 7.0]    # Aluno 3
])
```

Responda **sem usar laços `for`**:

1. Calcule a média de cada aluno (média por linha).
2. Transpose a matriz e calcule a média de cada matéria (que agora são as linhas).
3. Calcule a diferença entre as notas do Aluno 1 e do Aluno 2 (element-wise).
4. Aplique um bônus de +0.5 em todas as notas (broadcasting). Certifique-se que nenhuma nota ultrapasse 10 usando `np.clip()` — pesquise como funciona!

> 💡 **Dica para o item 4:** `np.clip(array, min, max)` limita os valores de um array entre um mínimo e máximo. O que acontece se a nota já for 9.8 e você somar 0.5?

### Exercício 5 — Desafio: Mini Análise de Dataset com Matrizes

**Enunciado:** Uma empresa de e-commerce tem os dados de 5 produtos em 4 regiões do Brasil (Norte, Nordeste, Sudeste, Sul), representando as **quantidades vendidas** no mês:

```python
quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto
```

Resolva **sem usar laços `for`**:

1. Calcule a receita total gerada por cada produto em todas as regiões (soma das colunas de cada linha × preço).
2. Calcule o total de unidades vendidas por região (soma de cada coluna).
3. Identifique qual produto e qual região têm o maior e o menor volume de vendas.
4. Crie uma matrix de receitas `(5, 4)` onde cada célula é `quantidade × preço_do_produto` para aquela região. *(Dica: use reshape ou broadcasting 2D.)*
5. Exiba a receita total por região.

> 💡 **Dica para o item 4:** Tente `quantidades * precos.reshape(5, 1)` — isso multiplica cada linha pelo preço correspondente daquele produto (broadcasting 2D).
