## ✏️ Exercícios de Fixação

In [1]:
import numpy as np

### Exercício 1 — Fácil: Criando e inspecionando matrizes

**Enunciado:** Crie as seguintes matrizes e exiba o `shape`, `ndim` e `size` de cada uma:

a) Uma matriz 3×3 com os valores de 1 a 9 (use `arange` + `reshape`).  
b) Uma matriz de zeros com 4 linhas e 2 colunas.  
c) A matriz identidade de tamanho 3.

> 💡 **Dica:** Para o item (a), crie primeiro o array com `np.arange(1, 10)` e depois use `.reshape(3, 3)`.

a) *Resposta*

In [2]:
matriz = np.arange(1, 10)
print(matriz)

matriz_3x3 = matriz.reshape(3, 3)
print('Matriz 3x3: \n', matriz_3x3)

print(f'shape: {matriz_3x3.shape}, size: {matriz_3x3.size}, ndim: {matriz_3x3.ndim}')



[1 2 3 4 5 6 7 8 9]
Matriz 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3), size: 9, ndim: 2


b) *Resposta*

In [3]:
matriz_zeros = np.zeros((4,2))
print("Matriz_zeros: \n", matriz_zeros)

print(f'shape: {matriz_zeros.shape}, size: {matriz_zeros.size}, ndim: {matriz_zeros.ndim}')

Matriz_zeros: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
shape: (4, 2), size: 8, ndim: 2


c) *Resposta*

In [4]:
matriz_ident = np.eye(3)
print('Matriz Identidade 3: \n', matriz_ident)
print(f'shape: {matriz_ident.shape}, size: {matriz_ident.size}, ndim: {matriz_ident.ndim}')

Matriz Identidade 3: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (3, 3), size: 9, ndim: 2


### Exercício 2 — Fácil: Indexação e fatiamento

**Enunciado:** Dada a matriz de temperaturas diárias de 3 cidades ao longo de 5 dias:

```python
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])
```

Extraia:
- A temperatura da Cidade B no 3º dia (índice 2).
- Todas as temperaturas da Cidade C.
- As temperaturas de todas as cidades no último dia.
- A submatriz das cidades A e B nos primeiros 3 dias.

> 💡 **Dica:** Para "último dia", use índice `-1` na coluna. Para a submatriz, lembre que o fim do slice é exclusivo.

In [5]:
temperaturas = np.array([
    [32, 33, 31, 29, 35],   # Cidade A
    [28, 27, 30, 26, 29],   # Cidade B
    [22, 24, 21, 23, 25]    # Cidade C
])

# Temperatura na Cidade B no 3º Dia
print('Temperatura do 3º Dia na Cidade B: ', temperaturas[1, 2])

#Todas as Temperaturas da Cidade C
print('Temperaturas da Cidade C: ', temperaturas[-1, :])

#Temperaturas de Todas as Cidades no último Dia
print('Temperaturas do último dia em todas as Cidades: ', temperaturas[:, -1])

#submatriz das Cidadades A e B nos 3 primeiros dias
print('Temperaturas das Cidades A e B do primeiro ao terceiro dia: \n', temperaturas[0:2, 0:3])

Temperatura do 3º Dia na Cidade B:  30
Temperaturas da Cidade C:  [22 24 21 23 25]
Temperaturas do último dia em todas as Cidades:  [35 29 25]
Temperaturas das Cidades A e B do primeiro ao terceiro dia: 
 [[32 33 31]
 [28 27 30]]


### Exercício 3 — Médio: Reshape, flatten e estatísticas por eixo

**Enunciado:** Você tem as vendas mensais de uma loja ao longo de um ano, registradas em um array 1D de 12 elementos (Janeiro a Dezembro):

```python
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])
```

1. Reorganize esse array em uma matriz `(4, 3)` onde cada linha representa um trimestre e cada coluna representa um mês dentro do trimestre.
2. Calcule o total de vendas por trimestre (soma por linha — `axis=1`).
3. Calcule a média de vendas por mês dentro de cada trimestre (já feito pelo item 2 se dividir por 3).
4. Identifique o trimestre com maior faturamento.
5. Use `flatten()` para recuperar o array original.

> 💡 **Dica:** Para o item 4, use `np.argmax()` no array de totais. Lembre que o índice retornado começa em 0 — some 1 para obter o número do trimestre.

In [6]:
vendas_ano = np.array([45, 52, 48, 60, 55, 70, 80, 78, 65, 58, 50, 90])

1. *Resposta*

In [7]:
#Array organizado por matriz 4x3

vendas_trimestre = vendas_ano.reshape(4, 3)
print("Vendas Trimestre: \n", vendas_trimestre)

Vendas Trimestre: 
 [[45 52 48]
 [60 55 70]
 [80 78 65]
 [58 50 90]]


2. *Resposta*

In [8]:
#Total de Vendas por Trimestre

print('Total de Vendas nos trimestres: ', np.sum(vendas_trimestre, axis=1))


Total de Vendas nos trimestres:  [145 185 223 198]


3. *Resposta*

In [9]:
#Média de Vendas por trimestre
print('Média de Vendas nos trimestres: ', np.mean(vendas_trimestre, axis=1))
print('Média de Vendas nos trimestres: ', np.sum(vendas_trimestre, axis=1)/3)

Média de Vendas nos trimestres:  [48.33333333 61.66666667 74.33333333 66.        ]
Média de Vendas nos trimestres:  [48.33333333 61.66666667 74.33333333 66.        ]


4. *Resposta*

In [10]:
#Trimestre com maior faturamento
total_trimestres = np.sum(vendas_trimestre, axis=1)
print('Máximo de Vendas nos trimestres: ', np.max(total_trimestres))

Máximo de Vendas nos trimestres:  223


5. *Resposta*

In [11]:
vendas_year = vendas_trimestre.flatten()
print("Array Original: ", vendas_year)

Array Original:  [45 52 48 60 55 70 80 78 65 58 50 90]


### Exercício 4 — Médio: Operações e transposição

**Enunciado:** Uma escola tem as notas de 3 alunos em 4 matérias:

```python
notas = np.array([
    [7.0, 8.5, 6.0, 9.0],   # Aluno 1: Mat, Port, Hist, Cien
    [9.0, 7.5, 8.0, 8.5],   # Aluno 2
    [6.5, 9.0, 7.5, 7.0]    # Aluno 3
])
```

Responda **sem usar laços `for`**:

1. Calcule a média de cada aluno (média por linha).
2. Transpose a matriz e calcule a média de cada matéria (que agora são as linhas).
3. Calcule a diferença entre as notas do Aluno 1 e do Aluno 2 (element-wise).
4. Aplique um bônus de +0.5 em todas as notas (broadcasting). Certifique-se que nenhuma nota ultrapasse 10 usando `np.clip()` — pesquise como funciona!

> 💡 **Dica para o item 4:** `np.clip(array, min, max)` limita os valores de um array entre um mínimo e máximo. O que acontece se a nota já for 9.8 e você somar 0.5?

In [38]:
notas = np.array([
    [7.0, 8.5, 6.0, 9.8],   # Aluno 1: Mat, Port, Hist, Cien
    [9.0, 7.5, 8.0, 8.5],   # Aluno 2
    [6.5, 9.0, 7.5, 7.0]    # Aluno 3
])

1. *Resposta*

In [39]:
aluno = np.mean(notas, axis=1)
print('A Média de cada Aluno é: ', aluno)

A Média de cada Aluno é:  [7.825 8.25  7.5  ]


2. *Resposta*

In [40]:
materia = notas.T
print('Matriz Transposta: \n', materia)
print('A média para cada disciplina é: ', np.mean(materia, axis=1))

Matriz Transposta: 
 [[7.  9.  6.5]
 [8.5 7.5 9. ]
 [6.  8.  7.5]
 [9.8 8.5 7. ]]
A média para cada disciplina é:  [7.5        8.33333333 7.16666667 8.43333333]


3. *Resposta*

In [41]:
print('A Diferença entre Aluno 1 e Aluno 2 é: ', notas[0, :] - notas[1, :])

A Diferença entre Aluno 1 e Aluno 2 é:  [-2.   1.  -2.   1.3]


4. *Resposta*

In [42]:
nota_com_bonus = notas + 0.5
print('As notas com bônus de 0.5 são: \n', nota_com_bonus)
print('\nAs notas corrigidas são: \n', np.clip(nota_com_bonus, 0, 10))

As notas com bônus de 0.5 são: 
 [[ 7.5  9.   6.5 10.3]
 [ 9.5  8.   8.5  9. ]
 [ 7.   9.5  8.   7.5]]

As notas corrigidas são: 
 [[ 7.5  9.   6.5 10. ]
 [ 9.5  8.   8.5  9. ]
 [ 7.   9.5  8.   7.5]]


### Exercício 5 — Desafio: Mini Análise de Dataset com Matrizes

**Enunciado:** Uma empresa de e-commerce tem os dados de 5 produtos em 4 regiões do Brasil (Norte, Nordeste, Sudeste, Sul), representando as **quantidades vendidas** no mês:

```python
quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])  # Preço de cada produto
```

Resolva **sem usar laços `for`**:

1. Calcule a receita total gerada por cada produto em todas as regiões (soma das colunas de cada linha × preço).
2. Calcule o total de unidades vendidas por região (soma de cada coluna).
3. Identifique qual produto e qual região têm o maior e o menor volume de vendas.
4. Crie uma matrix de receitas `(5, 4)` onde cada célula é `quantidade × preço_do_produto` para aquela região. *(Dica: use reshape ou broadcasting 2D.)*
5. Exiba a receita total por região.

> 💡 **Dica para o item 4:** Tente `quantidades * precos.reshape(5, 1)` — isso multiplica cada linha pelo preço correspondente daquele produto (broadcasting 2D).


In [32]:
#Quantidade de produtos por região
quantidades = np.array([
    [120, 340, 890, 210],   # Produto 1
    [ 80, 150, 560, 300],   # Produto 2
    [200, 420, 1100, 480],  # Produto 3
    [ 50,  90,  320, 180],  # Produto 4
    [310, 500, 1450, 620]   # Produto 5
])

#Preço por produto
precos = np.array([29.90, 49.90, 19.90, 89.90, 14.90])

1. *Resposta*

In [48]:

print('O Total de Receita Total por produto é: \n', np.sum(quantidades, axis=1) * precos)

O Total de Receita Total por produto é: 
 [46644. 54391. 43780. 57536. 42912.]


2. *Resposta*

In [34]:
print('Total de Unidades vendidas por região: \n', np.sum(quantidades, axis=0))

Total de Unidades vendidas por região: 
 [ 760 1500 4320 1790]


3. *Resposta*

In [37]:
print('O maior volume de vendas por produto: ', np.max(np.sum(quantidades, axis=1)))
print('O menor volume de vendas por produto: ', np.min(np.sum(quantidades, axis=1)))

print('O maior volume de vendas por região: ', np.max(np.sum(quantidades, axis=0)))
print('O menor volume de vendas por região: ', np.min(np.sum(quantidades, axis=0)))

O maior volume de vendas por produto:  2880
O menor volume de vendas por produto:  640
O maior volume de vendas por região:  4320
O menor volume de vendas por região:  760


4. *Resposta*

In [64]:
precos = precos.reshape(5,1)
print(precos.ndim)

matriz_receitas = quantidades * precos

print(matriz_receitas)


2
[[ 3588. 10166. 26611.  6279.]
 [ 3992.  7485. 27944. 14970.]
 [ 3980.  8358. 21890.  9552.]
 [ 4495.  8091. 28768. 16182.]
 [ 4619.  7450. 21605.  9238.]]


5. *Resposta*

In [65]:
print('A Receita Total por Região é: \n', np.sum(matriz_receitas, axis=0))

A Receita Total por Região é: 
 [ 20674.  41550. 126818.  56221.]
