In [1]:
import numpy as np

**EXERCICIO 1**

**Enunciado:** Você recebeu as temperaturas máximas (em °C) de uma cidade durante uma semana: `[32, 28, 35, 31, 29, 33, 36]`. Crie um array NumPy com esses valores e exiba: o array completo, seu `shape`, `dtype`, `ndim` e `size`.

In [2]:
temperaturas = np.array([32, 28, 35, 31, 29, 33, 36])

print(temperaturas.shape)
print(temperaturas.dtype)
print(temperaturas.ndim)
print(temperaturas.size)

(7,)
int64
1
7


**EXERCICIO 2**

**Enunciado:** Usando o array de temperaturas do exercício anterior `[32, 28, 35, 31, 29, 33, 36]`, extraia:
- A temperatura de quinta-feira (5º dia da semana)
- A temperatura do último dia
- As temperaturas do meio da semana (terça, quarta e quinta — índices 1, 2 e 3)

In [3]:
print(f'Quinta-feira {temperaturas[4]} ºC')
print(f'Último Dia - Domingo {temperaturas[-1]} ºC')
print(f'Terça, Quarta e Quinta {temperaturas[1:4]} ºC')

Quinta-feira 29 ºC
Último Dia - Domingo 36 ºC
Terça, Quarta e Quinta [28 35 31] ºC


**EXERCICIO 3**

**Enunciado:** Uma padaria registrou suas vendas (em R$) de segunda a sábado: `[450.00, 320.50, 510.75, 489.00, 605.25, 780.50]`. Com esse array:

1. Calcule o total faturado na semana.
2. Calcule a média diária de vendas.
3. Identifique o menor e o maior faturamento.
4. Aplique um desconto de 5% em todos os dias (simule uma promoção onde a padaria deu 5% de cashback). Exiba os valores após o desconto.

In [4]:
vendas = np.array([450.00, 320.50, 510.75, 489.00, 605.25, 780.50])

print(f'O Total de Vendas foi R$ {np.sum(vendas):,.2f}')
print(f'A Média de Vendas foi R$ {np.mean(vendas):,.2f}')
print(f'A venda mínima foi de R$ {np.min(vendas):,.2f}')
print(f'A venda máxima foi de R$ {np.max(vendas):,.2f}')
print('\n--------------------\n')

vendas_desconto = vendas * 0.95


for i in np.arange(0, vendas_desconto.size):
    print(f'O valor com desconto é de R$ {vendas_desconto[i]:,.2f}\n')
    


#print(f'\nO valor com desconto é R$ {vendas_desconto[3]:,.2f}')


O Total de Vendas foi R$ 3,156.00
A Média de Vendas foi R$ 526.00
A venda mínima foi de R$ 320.50
A venda máxima foi de R$ 780.50

--------------------

O valor com desconto é de R$ 427.50

O valor com desconto é de R$ 304.47

O valor com desconto é de R$ 485.21

O valor com desconto é de R$ 464.55

O valor com desconto é de R$ 574.99

O valor com desconto é de R$ 741.47



**EXERCICIO 4**

**Enunciado:**

a) Use `np.arange()` para criar um array com todos os números pares de 0 a 20 (inclusive).  
b) Use `np.linspace()` para criar um array com exatamente 7 valores igualmente espaçados entre 0% e 100% (representando faixas de desconto de uma promoção progressiva).  
c) Exiba ambos os arrays e seus respectivos `shape`.

In [5]:
numeros_pares = np.arange(0, 21, 2)
print(numeros_pares)

taxas_desconto = np.linspace(0, 100, 7)

for i in np.arange(0, taxas_desconto.size):
    print(f'A Taxa {i} de desconto é de {taxas_desconto[i]:,.2f}%\n')

print(numeros_pares.shape)
print(taxas_desconto.shape)

[ 0  2  4  6  8 10 12 14 16 18 20]
A Taxa 0 de desconto é de 0.00%

A Taxa 1 de desconto é de 16.67%

A Taxa 2 de desconto é de 33.33%

A Taxa 3 de desconto é de 50.00%

A Taxa 4 de desconto é de 66.67%

A Taxa 5 de desconto é de 83.33%

A Taxa 6 de desconto é de 100.00%

(11,)
(7,)


**EXERCICIO 5**

**Enunciado:** Duas equipes de vendas registraram seus resultados mensais ao longo de 6 meses:

- **Equipe A:** `[42000, 38500, 51000, 47300, 55800, 49200]`
- **Equipe B:** `[39000, 41200, 48700, 52000, 44600, 53100]`

Resolva as seguintes questões **sem usar laços `for`** (use apenas operações NumPy):

In [6]:
equipe_A = np.array([42000, 38500, 51000, 47300, 55800, 49200])
equipe_B = np.array([39000, 41200, 48700, 52000, 44600, 53100])

1. Qual equipe teve o maior faturamento **total** em 6 meses?

In [7]:
total_A = np.sum(equipe_A)
total_B = np.sum(equipe_B)

print(f'O total vendido pela equipe A foi de R$ {total_A:,.2f}')
print(f'O total vendido pela equipe B foi de R$ {total_B:,.2f}')

if total_A > total_B:
    print(f'A Equipe A teve o maior faturamento total do semestre vendendo R$ {total_A:,.2f}')
else:
    print(f'A Equipe B teve o maior faturamento total do semestre vendendo R$ {total_B:,.2f}')

O total vendido pela equipe A foi de R$ 283,800.00
O total vendido pela equipe B foi de R$ 278,600.00
A Equipe A teve o maior faturamento total do semestre vendendo R$ 283,800.00


2. Calcule a diferença de vendas mês a mês (Equipe A − Equipe B). Em quais meses a Equipe A superou a Equipe B?

In [8]:
meses = np.array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho'])
diferenca_vendas = equipe_A - equipe_B

print(diferenca_vendas)

for i in np.arange(0, diferenca_vendas.size):
    if diferenca_vendas[i] > 0:
        print(f'A equipe A vendeu mais no mes de {meses[i]} com adicional de R$ {diferenca_vendas[i]:,.2f} vendidos')
    else:
        print(f'A equipe B vendeu mais no mes de {meses[i]} com adicional de R$ {(diferenca_vendas[i] * -1):,.2f} vendidos')

[ 3000 -2700  2300 -4700 11200 -3900]
A equipe A vendeu mais no mes de Janeiro com adicional de R$ 3,000.00 vendidos
A equipe B vendeu mais no mes de Fevereiro com adicional de R$ 2,700.00 vendidos
A equipe A vendeu mais no mes de Março com adicional de R$ 2,300.00 vendidos
A equipe B vendeu mais no mes de Abril com adicional de R$ 4,700.00 vendidos
A equipe A vendeu mais no mes de Maio com adicional de R$ 11,200.00 vendidos
A equipe B vendeu mais no mes de Junho com adicional de R$ 3,900.00 vendidos


3. Calcule a média de cada equipe e o desvio padrão. Qual equipe é mais consistente (menor desvio)?

In [9]:
media_A = np.mean(equipe_A)
media_B = np.mean(equipe_B)

desvio_A = np.std(equipe_A)
desvio_B = np.std(equipe_B)

print(f'Media A: {media_A:,.2f}, \nDesvio A: {desvio_A:,.2f}, \nMedia B: {media_B:,.2f}, \nDesvio B: {desvio_B:,.2f}\n')

if desvio_A < desvio_B:
    print(f'A Equipe A é mais consistente em suas vendas, com média semestral de R$ {media_A:,.2f} e desvio padrão de R$ {desvio_A:,.2f}')
else:
    print(f'A Equipe B é mais consistente em suas vendas, com média semestral de R$ {media_B:,.2f} e desvio padrão de R$ {desvio_B:,.2f}')

Media A: 47,300.00, 
Desvio A: 5,702.05, 
Media B: 46,433.33, 
Desvio B: 5,268.99

A Equipe B é mais consistente em suas vendas, com média semestral de R$ 46,433.33 e desvio padrão de R$ 5,268.99


4. Crie um array `bonus` onde cada equipe recebe 8% do seu próprio faturamento mensal como bônus. Exiba o total de bônus de cada equipe.

In [10]:
bonus_A = equipe_A * 0.08
bonus_B = equipe_B * 0.08

total_bonus_A = np.sum(bonus_A)
total_bonus_B = np.sum(bonus_B)

print(bonus_A, bonus_B)

print(f'A Equipe A ganhou um total de R$ {total_bonus_A} de bonus neste semestre')
print(f'A Equipe B ganhou um total de R$ {total_bonus_B} de bonus neste semestre')

[3360. 3080. 4080. 3784. 4464. 3936.] [3120. 3296. 3896. 4160. 3568. 4248.]
A Equipe A ganhou um total de R$ 22704.0 de bonus neste semestre
A Equipe B ganhou um total de R$ 22288.0 de bonus neste semestre


In [22]:
import numpy as np
trid = np.array([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]])

In [23]:
print(trid.size)
print(trid.dtype)
print(trid.ndim)

9
int64
3
